"""initial schema

Revision ID: daa89b447546
Revises: 
Create Date: 2026-03-04 04:46:57.694366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa89b447546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
     # commands auto generated by Alembic
    op.create_table('games',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('play_time_minutes', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'full', 'cancelled', 'completed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('favorite_games',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('friendships',
    sa.Column('user_id_1', sa.String(length=50), nullable=False),
    sa.Column('user_id_2', sa.String(length=50), nullable=False),
    sa.Column('action_user_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id_1', 'user_id_2')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('event_participants',
    sa.Column('participant_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'waitlist'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=50), nullable=False),
    sa.Column('reviewer_id', sa.String(length=50), nullable=False),
    sa.Column('reviewed_user_id', sa.String(length=50), nullable=True),
    sa.Column('reviewed_event_id', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # end Alembic commands


def downgrade():
    # commands auto generated by Alembic
    op.drop_table('reviews')
    op.drop_table('event_participants')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('friendships')
    op.drop_table('favorite_games')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('games')
    # end Alembic commands
